Fix Read-me and Consecutive-Command
AY2425S1-CS2103T-W08-4/tp pull request #157
Opened 2024-11-05 13:39 UTC by martout2002

fixes #156

2024-11-05 23:03 UTC, Hoodini231 requested changes
LGTM just need fix readme prefixs

2024-11-06 02:35 UTC, wenjebs commented on docs/UserGuide.md
> +Format: `add /name NAME /class CLASS /phone PHONE_NUMBER [t/TAG]…​`
remember to change this prefix as well!

2024-11-06 02:35 UTC, wenjebs commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> +        Command command;
lgtm

2024-11-06 05:07 UTC, Hoodini231 approved these changes

2024-11-06 05:07 UTC, Hoodini231 commented
Thank you for the revisions Martin !

2024-11-06 08:04 UTC, merged